### ISSUE TITLE
S2 parametrization math differs from paper

### ISSUE THREAD

**Issue by protobits** [rock-slam/slam-mtk#9]
Hi,
I've found that the code (line https://github.com/rock-slam/slam-mtk/blob/328d3f2e1cb19150f2c6c2cde5100400d216657b/mtk/types/S2.hpp#L130 ) computes norm(y,z), whereas equation 113 of Information Fusion paper computes norm(x,z). I've believe the code is correct but I wanted to confirm.

**Comment by chhtz** [comment]
Good catch! Looks like we made a typo in the paper. Only with `r=norm(y,z)` the second column of `R` always has unit-norm. (And in retrospect I'm not happy with using x and y in (113) as well as (112) ...)

**Comment by protobits** [comment]
Ok! Thank you for your response.

**Comment by chhtz** [comment]
I'm closing this, since it is not an issue with the code.
